// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.DialogParts
{
#nullable enable
    public partial record DecisionDialogPart : DialogFramework.Abstractions.DomainModel.DialogParts.IDecisionDialogPart
    {
        public string Id
        {
            get;
        }

        public CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDecision> Decisions
        {
            get;
        }

        public string DefaultNextPartId
        {
            get;
        }

        public DecisionDialogPart(string id, CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDecision> decisions, string defaultNextPartId)
        {
            if (decisions == null) throw new System.ArgumentNullException("decisions");
            if (defaultNextPartId == null) throw new System.ArgumentNullException("defaultNextPartId");
            this.Id = id;
            this.Decisions = decisions;
            this.DefaultNextPartId = defaultNextPartId;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

