// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.DialogParts
{
#nullable enable
    public partial record ErrorDialogPart : DialogFramework.Abstractions.DomainModel.DialogParts.IErrorDialogPart
    {
        public string ErrorMessage
        {
            get;
        }

        public System.Exception? Exception
        {
            get;
        }

        public string Id
        {
            get;
        }

        public ErrorDialogPart(string errorMessage, System.Exception? exception, string id)
        {
            this.ErrorMessage = errorMessage;
            this.Exception = exception;
            this.Id = id;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

