// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace DialogFramework.Domain.Builders
{
    public abstract partial class DialogPartBuilder
    {
        private string _id;

        private ExpressionFramework.Domain.Builders.EvaluatableBuilder? _condition;

        private string _title;

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.String>.Default.Equals(_id!, value!);
                _id = value;
                if (hasChanged) HandlePropertyChanged(nameof(Id));
            }
        }

        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public ExpressionFramework.Domain.Builders.EvaluatableBuilder? Condition
        {
            get
            {
                return _condition;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<ExpressionFramework.Domain.Builders.EvaluatableBuilder>.Default.Equals(_condition!, value!);
                _condition = value;
                if (hasChanged) HandlePropertyChanged(nameof(Condition));
            }
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string Title
        {
            get
            {
                return _title;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.String>.Default.Equals(_title!, value!);
                _title = value;
                if (hasChanged) HandlePropertyChanged(nameof(Title));
            }
        }

        protected DialogPartBuilder(DialogFramework.Domain.DialogPart source)
        {
            _id = source.Id;
            _condition = source.Condition?.ToBuilder()!;
            _title = source.Title;
        }

        protected DialogPartBuilder()
        {
            _id = string.Empty;
            _title = string.Empty;
            SetDefaultValues();
        }

        public abstract DialogFramework.Domain.DialogPart Build();

        partial void SetDefaultValues();

        public static implicit operator DialogFramework.Domain.DialogPart(DialogPartBuilder entity)
        {
            return entity.Build();
        }

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    public abstract partial class DialogPartResultBuilder
    {
        private string _partId;

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string PartId
        {
            get
            {
                return _partId;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.String>.Default.Equals(_partId!, value!);
                _partId = value;
                if (hasChanged) HandlePropertyChanged(nameof(PartId));
            }
        }

        protected DialogPartResultBuilder(DialogFramework.Domain.DialogPartResult source)
        {
            _partId = source.PartId;
        }

        protected DialogPartResultBuilder()
        {
            _partId = string.Empty;
            SetDefaultValues();
        }

        public abstract DialogFramework.Domain.DialogPartResult Build();

        partial void SetDefaultValues();

        public static implicit operator DialogFramework.Domain.DialogPartResult(DialogPartResultBuilder entity)
        {
            return entity.Build();
        }

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    public abstract partial class ValidationRuleBuilder
    {
        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        protected ValidationRuleBuilder(DialogFramework.Domain.ValidationRule source)
        {
        }

        protected ValidationRuleBuilder()
        {
            SetDefaultValues();
        }

        public abstract DialogFramework.Domain.ValidationRule Build();

        partial void SetDefaultValues();

        public static implicit operator DialogFramework.Domain.ValidationRule(ValidationRuleBuilder entity)
        {
            return entity.Build();
        }

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
#nullable disable
