// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.10
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace DialogFramework.Domain.DialogPartResults
{
    public partial class MultipleQuestionDialogPartResult<T> : DialogFramework.Domain.DialogPartResult
    {
        private System.Collections.ObjectModel.ObservableCollection<T> _values;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public System.Collections.ObjectModel.ObservableCollection<T> Values
        {
            get
            {
                return _values;
            }
            private set
            {
                bool hasChanged = !EqualityComparer<System.Collections.ObjectModel.ObservableCollection<T>>.Default.Equals(_values, value);
                _values = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Values));
            }
        }

        public MultipleQuestionDialogPartResult(System.Collections.Generic.IEnumerable<T> values, string partId) : base(partId)
        {
            if (values is null) throw new System.ArgumentNullException(nameof(values));
            this._values = new System.Collections.ObjectModel.ObservableCollection<T>(values);
        }

        public override DialogFramework.Domain.Builders.DialogPartResultBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public DialogFramework.Domain.Builders.DialogPartResults.MultipleQuestionDialogPartResultBuilder<T> ToTypedBuilder()
        {
            return new DialogFramework.Domain.Builders.DialogPartResults.MultipleQuestionDialogPartResultBuilder<T>(this);
        }
    }
    public partial class SingleQuestionDialogPartResult<T> : DialogFramework.Domain.DialogPartResult
    {
        private T? _value;

        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public T? Value
        {
            get
            {
                return _value;
            }
            private set
            {
                bool hasChanged = !EqualityComparer<T>.Default.Equals(_value, value);
                _value = value;
                if (hasChanged) HandlePropertyChanged(nameof(Value));
            }
        }

        public SingleQuestionDialogPartResult(T? value, string partId) : base(partId)
        {
            this._value = value;
        }

        public override DialogFramework.Domain.Builders.DialogPartResultBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public DialogFramework.Domain.Builders.DialogPartResults.SingleQuestionDialogPartResultBuilder<T> ToTypedBuilder()
        {
            return new DialogFramework.Domain.Builders.DialogPartResults.SingleQuestionDialogPartResultBuilder<T>(this);
        }
    }
}
#nullable disable
