// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.DialogParts.Builders
{
#nullable enable
    public partial class AbortedDialogPartBuilder
    {
        public string Message
        {
            get
            {
                return _messageDelegate.Value;
            }
            set
            {
                _messageDelegate = new (() => value);
            }
        }

        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.Domains.DialogState State
        {
            get
            {
                return _stateDelegate.Value;
            }
            set
            {
                _stateDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IAbortedDialogPart Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.DialogParts.AbortedDialogPart(Message, Id, State);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public AbortedDialogPartBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public AbortedDialogPartBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public AbortedDialogPartBuilder WithMessage(System.Func<string> messageDelegate)
        {
            _messageDelegate = new (messageDelegate);
            return this;
        }

        public AbortedDialogPartBuilder WithMessage(string message)
        {
            Message = message;
            return this;
        }

        public AbortedDialogPartBuilder WithState(DialogFramework.Abstractions.DomainModel.Domains.DialogState state)
        {
            State = state;
            return this;
        }

        public AbortedDialogPartBuilder WithState(System.Func<DialogFramework.Abstractions.DomainModel.Domains.DialogState> stateDelegate)
        {
            _stateDelegate = new (stateDelegate);
            return this;
        }

        public AbortedDialogPartBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _messageDelegate = new (() => string.Empty);
            _idDelegate = new (() => string.Empty);
            _stateDelegate = new (() => DialogFramework.Abstractions.DomainModel.Domains.DialogState.Aborted);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public AbortedDialogPartBuilder(DialogFramework.Abstractions.DomainModel.DialogParts.IAbortedDialogPart source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _messageDelegate = new (() => source.Message);
            _idDelegate = new (() => source.Id);
            _stateDelegate = new (() => source.State);
        }

        private System.Lazy<string> _messageDelegate;

        private System.Lazy<string> _idDelegate;

        private System.Lazy<DialogFramework.Abstractions.DomainModel.Domains.DialogState> _stateDelegate;
    }
#nullable restore
}

