// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.DialogParts.Builders
{
#nullable enable
    public partial class CompletedDialogPartBuilder
    {
        public string Message
        {
            get
            {
                return _messageDelegate.Value;
            }
            set
            {
                _messageDelegate = new (() => value);
            }
        }

        public DialogFramework.UniversalModel.DomainModel.Builders.DialogPartGroupBuilder Group
        {
            get
            {
                return _groupDelegate.Value;
            }
            set
            {
                _groupDelegate = new (() => value);
            }
        }

        public string Heading
        {
            get
            {
                return _headingDelegate.Value;
            }
            set
            {
                _headingDelegate = new (() => value);
            }
        }

        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.Domains.DialogState State
        {
            get
            {
                return _stateDelegate.Value;
            }
            set
            {
                _stateDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.ICompletedDialogPart Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.DialogParts.CompletedDialogPart(Message, Group?.Build(), Heading, Id, State);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public CompletedDialogPartBuilder WithGroup(DialogFramework.UniversalModel.DomainModel.Builders.DialogPartGroupBuilder group)
        {
            Group = group;
            return this;
        }

        public CompletedDialogPartBuilder WithGroup(System.Func<DialogFramework.UniversalModel.DomainModel.Builders.DialogPartGroupBuilder> groupDelegate)
        {
            _groupDelegate = new (groupDelegate);
            return this;
        }

        public CompletedDialogPartBuilder WithHeading(System.Func<string> headingDelegate)
        {
            _headingDelegate = new (headingDelegate);
            return this;
        }

        public CompletedDialogPartBuilder WithHeading(string heading)
        {
            Heading = heading;
            return this;
        }

        public CompletedDialogPartBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public CompletedDialogPartBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public CompletedDialogPartBuilder WithMessage(System.Func<string> messageDelegate)
        {
            _messageDelegate = new (messageDelegate);
            return this;
        }

        public CompletedDialogPartBuilder WithMessage(string message)
        {
            Message = message;
            return this;
        }

        public CompletedDialogPartBuilder WithState(DialogFramework.Abstractions.DomainModel.Domains.DialogState state)
        {
            State = state;
            return this;
        }

        public CompletedDialogPartBuilder WithState(System.Func<DialogFramework.Abstractions.DomainModel.Domains.DialogState> stateDelegate)
        {
            _stateDelegate = new (stateDelegate);
            return this;
        }

        public CompletedDialogPartBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _messageDelegate = new (() => string.Empty);
            _groupDelegate = new (() => default);
            _headingDelegate = new (() => string.Empty);
            _idDelegate = new (() => string.Empty);
            _stateDelegate = new (() => DialogFramework.Abstractions.DomainModel.Domains.DialogState.Completed);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public CompletedDialogPartBuilder(DialogFramework.Abstractions.DomainModel.DialogParts.ICompletedDialogPart source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _messageDelegate = new (() => source.Message);
            _groupDelegate = new(() => new DialogFramework.UniversalModel.DomainModel.Builders.DialogPartGroupBuilder(source.Group));
            _headingDelegate = new (() => source.Heading);
            _idDelegate = new (() => source.Id);
            _stateDelegate = new (() => source.State);
        }

        private System.Lazy<string> _messageDelegate;

        private System.Lazy<DialogFramework.UniversalModel.DomainModel.Builders.DialogPartGroupBuilder> _groupDelegate;

        private System.Lazy<string> _headingDelegate;

        private System.Lazy<string> _idDelegate;

        private System.Lazy<DialogFramework.Abstractions.DomainModel.Domains.DialogState> _stateDelegate;
    }
#nullable restore
}

