// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.DialogParts.Builders
{
#nullable enable
    public partial class DecisionDialogPartBuilder
    {
        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.Domains.DialogState State
        {
            get
            {
                return _stateDelegate.Value;
            }
            set
            {
                _stateDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<DecisionBuilder> Decisions
        {
            get;
            set;
        }

        public DecisionDialogPartBuilder AddDecisions(params DecisionBuilder[] decisions)
        {
            if (decisions != null)
            {
                Decisions.AddRange(decisions);
            }
            return this;
        }

        public DecisionDialogPartBuilder AddDecisions(System.Collections.Generic.IEnumerable<DecisionBuilder> decisions)
        {
            return AddDecisions(decisions.ToArray());
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IDecisionDialogPart Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.DialogParts.DecisionDialogPart(Id, State, new CrossCutting.Common.ValueCollection<Decision>(Decisions.Select(x => x.Build())));
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DecisionDialogPartBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public DecisionDialogPartBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public DecisionDialogPartBuilder WithState(DialogFramework.Abstractions.DomainModel.Domains.DialogState state)
        {
            State = state;
            return this;
        }

        public DecisionDialogPartBuilder WithState(System.Func<DialogFramework.Abstractions.DomainModel.Domains.DialogState> stateDelegate)
        {
            _stateDelegate = new (stateDelegate);
            return this;
        }

        public DecisionDialogPartBuilder()
        {
            Decisions = new System.Collections.Generic.List<DecisionBuilder>();
            #pragma warning disable CS8603 // Possible null reference return.
            _idDelegate = new (() => string.Empty);
            _stateDelegate = new (() => DialogFramework.Abstractions.DomainModel.Domains.DialogState.InProgress);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DecisionDialogPartBuilder(DialogFramework.Abstractions.DomainModel.DialogParts.IDecisionDialogPart source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            Decisions = new System.Collections.Generic.List<DecisionBuilder>();
            _idDelegate = new (() => source.Id);
            _stateDelegate = new (() => source.State);
            // skip: Decisions;
        }

        private System.Lazy<string> _idDelegate;

        private System.Lazy<DialogFramework.Abstractions.DomainModel.Domains.DialogState> _stateDelegate;
    }
#nullable restore
}

