// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.DialogParts.Builders
{
#nullable enable
    public partial class ErrorDialogPartBuilder
    {
        public string ErrorMessage
        {
            get
            {
                return _errorMessageDelegate.Value;
            }
            set
            {
                _errorMessageDelegate = new (() => value);
            }
        }

        public System.Exception? Exception
        {
            get
            {
                return _exceptionDelegate.Value;
            }
            set
            {
                _exceptionDelegate = new (() => value);
            }
        }

        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.Domains.DialogState State
        {
            get
            {
                return _stateDelegate.Value;
            }
            set
            {
                _stateDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IErrorDialogPart Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.DialogParts.ErrorDialogPart(ErrorMessage, Exception, Id, State);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public ErrorDialogPartBuilder WithErrorMessage(System.Func<string> errorMessageDelegate)
        {
            _errorMessageDelegate = new (errorMessageDelegate);
            return this;
        }

        public ErrorDialogPartBuilder WithErrorMessage(string errorMessage)
        {
            ErrorMessage = errorMessage;
            return this;
        }

        public ErrorDialogPartBuilder WithException(System.Exception? exception)
        {
            Exception = exception;
            return this;
        }

        public ErrorDialogPartBuilder WithException(System.Func<System.Exception?> exceptionDelegate)
        {
            _exceptionDelegate = new (exceptionDelegate);
            return this;
        }

        public ErrorDialogPartBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public ErrorDialogPartBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public ErrorDialogPartBuilder WithState(DialogFramework.Abstractions.DomainModel.Domains.DialogState state)
        {
            State = state;
            return this;
        }

        public ErrorDialogPartBuilder WithState(System.Func<DialogFramework.Abstractions.DomainModel.Domains.DialogState> stateDelegate)
        {
            _stateDelegate = new (stateDelegate);
            return this;
        }

        public ErrorDialogPartBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _errorMessageDelegate = new (() => string.Empty);
            _exceptionDelegate = new (() => default);
            _idDelegate = new (() => string.Empty);
            _stateDelegate = new (() => DialogFramework.Abstractions.DomainModel.Domains.DialogState.ErrorOccured);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public ErrorDialogPartBuilder(DialogFramework.Abstractions.DomainModel.DialogParts.IErrorDialogPart source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _errorMessageDelegate = new (() => source.ErrorMessage);
            _exceptionDelegate = new (() => source.Exception);
            _idDelegate = new (() => source.Id);
            _stateDelegate = new (() => source.State);
        }

        private System.Lazy<string> _errorMessageDelegate;

        private System.Lazy<System.Exception?> _exceptionDelegate;

        private System.Lazy<string> _idDelegate;

        private System.Lazy<DialogFramework.Abstractions.DomainModel.Domains.DialogState> _stateDelegate;
    }
#nullable restore
}

