// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core
{
#nullable enable
    public partial record DialogContext : DialogFramework.Abstractions.IDialogContext
    {
        public string Id
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.IDialogIdentifier CurrentDialogIdentifier
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.IDialogPart CurrentPart
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.IDialogPartGroup? CurrentGroup
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.Domains.DialogState CurrentState
        {
            get;
        }

        public CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPartResult> Answers
        {
            get;
        }

        public System.Exception? Exception
        {
            get;
        }

        public DialogContext(string id, DialogFramework.Abstractions.DomainModel.IDialogIdentifier currentDialogIdentifier, DialogFramework.Abstractions.DomainModel.IDialogPart currentPart, DialogFramework.Abstractions.DomainModel.IDialogPartGroup? currentGroup, DialogFramework.Abstractions.DomainModel.Domains.DialogState currentState, CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPartResult> answers, System.Exception? exception)
        {
            if (currentDialogIdentifier == null) throw new System.ArgumentNullException("currentDialogIdentifier");
            if (currentPart == null) throw new System.ArgumentNullException("currentPart");
            if (answers == null) throw new System.ArgumentNullException("answers");
            this.Id = id;
            this.CurrentDialogIdentifier = currentDialogIdentifier;
            this.CurrentPart = currentPart;
            this.CurrentGroup = currentGroup;
            this.CurrentState = currentState;
            this.Answers = answers;
            this.Exception = exception;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

