global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.Linq;
global using CrossCutting.Common;
global using DialogFramework.Abstractions;
global using DialogFramework.Abstractions.DomainModel;
global using DialogFramework.Abstractions.DomainModel.DialogParts;
global using DialogFramework.Abstractions.DomainModel.Domains;
