// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.DialogParts
{
#nullable enable
    public partial record CompletedDialogPart : DialogFramework.Abstractions.DomainModel.DialogParts.ICompletedDialogPart
    {
        public string Message
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.IDialogPartGroup Group
        {
            get;
        }

        public string Heading
        {
            get;
        }

        public string Id
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.Domains.DialogState State
        {
            get;
        }

        public CompletedDialogPart(string message, DialogFramework.Abstractions.DomainModel.IDialogPartGroup group, string heading, string id, DialogFramework.Abstractions.DomainModel.Domains.DialogState state)
        {
            if (group == null) throw new System.ArgumentNullException("group");
            this.Message = message;
            this.Group = group;
            this.Heading = heading;
            this.Id = id;
            this.State = state;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

