// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.DialogParts
{
#nullable enable
    public partial record RedirectDialogPart : DialogFramework.Abstractions.DomainModel.DialogParts.IRedirectDialogPart
    {
        public DialogFramework.Abstractions.DomainModel.IDialogMetadata RedirectDialogMetadata
        {
            get;
        }

        public string Id
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.Domains.DialogState State
        {
            get;
        }

        public RedirectDialogPart(DialogFramework.Abstractions.DomainModel.IDialogMetadata redirectDialogMetadata, string id, DialogFramework.Abstractions.DomainModel.Domains.DialogState state)
        {
            if (redirectDialogMetadata == null) throw new System.ArgumentNullException("redirectDialogMetadata");
            this.RedirectDialogMetadata = redirectDialogMetadata;
            this.Id = id;
            this.State = state;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

