// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.DialogParts.Builders
{
#nullable enable
    public partial class DecisionDialogPartBuilder
    {
        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DecisionBuilder> Decisions
        {
            get;
            set;
        }

        public string DefaultNextPartId
        {
            get
            {
                return _defaultNextPartIdDelegate.Value;
            }
            set
            {
                _defaultNextPartIdDelegate = new (() => value);
            }
        }

        public DecisionDialogPartBuilder AddDecisions(params DialogFramework.Core.DomainModel.Builders.DecisionBuilder[] decisions)
        {
            if (decisions != null)
            {
                Decisions.AddRange(decisions);
            }
            return this;
        }

        public DecisionDialogPartBuilder AddDecisions(System.Collections.Generic.IEnumerable<DialogFramework.Core.DomainModel.Builders.DecisionBuilder> decisions)
        {
            return AddDecisions(decisions.ToArray());
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IDecisionDialogPart Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.Core.DomainModel.DialogParts.DecisionDialogPart(Id, new CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDecision>(Decisions.Select(x => x.Build())), DefaultNextPartId);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DecisionDialogPartBuilder WithDefaultNextPartId(System.Func<string> defaultNextPartIdDelegate)
        {
            _defaultNextPartIdDelegate = new (defaultNextPartIdDelegate);
            return this;
        }

        public DecisionDialogPartBuilder WithDefaultNextPartId(string defaultNextPartId)
        {
            DefaultNextPartId = defaultNextPartId;
            return this;
        }

        public DecisionDialogPartBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public DecisionDialogPartBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public DecisionDialogPartBuilder()
        {
            Decisions = new System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DecisionBuilder>();
            #pragma warning disable CS8603 // Possible null reference return.
            _idDelegate = new (() => string.Empty);
            _defaultNextPartIdDelegate = new (() => string.Empty);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DecisionDialogPartBuilder(DialogFramework.Abstractions.DomainModel.DialogParts.IDecisionDialogPart source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            Decisions = new System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DecisionBuilder>();
            _idDelegate = new (() => source.Id);
            // skip: Decisions;
            _defaultNextPartIdDelegate = new (() => string.Empty);
        }

        private System.Lazy<string> _idDelegate;

        private System.Lazy<string> _defaultNextPartIdDelegate;
    }
#nullable restore
}

