// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.DialogParts.Builders
{
#nullable enable
    public partial class MessageDialogPartBuilder
    {
        public string Message
        {
            get
            {
                return _messageDelegate.Value;
            }
            set
            {
                _messageDelegate = new (() => value);
            }
        }

        public DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder Group
        {
            get
            {
                return _groupDelegate.Value;
            }
            set
            {
                _groupDelegate = new (() => value);
            }
        }

        public string Heading
        {
            get
            {
                return _headingDelegate.Value;
            }
            set
            {
                _headingDelegate = new (() => value);
            }
        }

        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IMessageDialogPart Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.Core.DomainModel.DialogParts.MessageDialogPart(Message, Group?.Build(), Heading, Id);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public MessageDialogPartBuilder WithGroup(DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder group)
        {
            Group = group;
            return this;
        }

        public MessageDialogPartBuilder WithGroup(System.Func<DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder> groupDelegate)
        {
            _groupDelegate = new (groupDelegate);
            return this;
        }

        public MessageDialogPartBuilder WithHeading(System.Func<string> headingDelegate)
        {
            _headingDelegate = new (headingDelegate);
            return this;
        }

        public MessageDialogPartBuilder WithHeading(string heading)
        {
            Heading = heading;
            return this;
        }

        public MessageDialogPartBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public MessageDialogPartBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public MessageDialogPartBuilder WithMessage(System.Func<string> messageDelegate)
        {
            _messageDelegate = new (messageDelegate);
            return this;
        }

        public MessageDialogPartBuilder WithMessage(string message)
        {
            Message = message;
            return this;
        }

        public MessageDialogPartBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _messageDelegate = new (() => string.Empty);
            _groupDelegate = new (() => default);
            _headingDelegate = new (() => string.Empty);
            _idDelegate = new (() => string.Empty);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public MessageDialogPartBuilder(DialogFramework.Abstractions.DomainModel.DialogParts.IMessageDialogPart source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _messageDelegate = new (() => source.Message);
            _groupDelegate = new(() => new DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder(source.Group));
            _headingDelegate = new (() => source.Heading);
            _idDelegate = new (() => source.Id);
        }

        private System.Lazy<string> _messageDelegate;

        private System.Lazy<DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder> _groupDelegate;

        private System.Lazy<string> _headingDelegate;

        private System.Lazy<string> _idDelegate;
    }
#nullable restore
}

