// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.DialogParts.Builders
{
#nullable enable
    public partial class QuestionDialogPartBuilder
    {
        public string Title
        {
            get
            {
                return _titleDelegate.Value;
            }
            set
            {
                _titleDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DialogPartResultDefinitionBuilder> Results
        {
            get;
            set;
        }

        public System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.QuestionDialogPartValidatorBuilder> Validators
        {
            get;
            set;
        }

        public System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DialogValidationResultBuilder> ValidationErrors
        {
            get;
            set;
        }

        public DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder Group
        {
            get
            {
                return _groupDelegate.Value;
            }
            set
            {
                _groupDelegate = new (() => value);
            }
        }

        public string Heading
        {
            get
            {
                return _headingDelegate.Value;
            }
            set
            {
                _headingDelegate = new (() => value);
            }
        }

        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public QuestionDialogPartBuilder AddResults(params DialogFramework.Core.DomainModel.Builders.DialogPartResultDefinitionBuilder[] results)
        {
            if (results != null)
            {
                Results.AddRange(results);
            }
            return this;
        }

        public QuestionDialogPartBuilder AddResults(System.Collections.Generic.IEnumerable<DialogFramework.Core.DomainModel.Builders.DialogPartResultDefinitionBuilder> results)
        {
            return AddResults(results.ToArray());
        }

        public QuestionDialogPartBuilder AddValidationErrors(params DialogFramework.Core.DomainModel.Builders.DialogValidationResultBuilder[] validationErrors)
        {
            if (validationErrors != null)
            {
                ValidationErrors.AddRange(validationErrors);
            }
            return this;
        }

        public QuestionDialogPartBuilder AddValidationErrors(System.Collections.Generic.IEnumerable<DialogFramework.Core.DomainModel.Builders.DialogValidationResultBuilder> validationErrors)
        {
            return AddValidationErrors(validationErrors.ToArray());
        }

        public QuestionDialogPartBuilder AddValidators(params DialogFramework.Core.DomainModel.Builders.QuestionDialogPartValidatorBuilder[] validators)
        {
            if (validators != null)
            {
                Validators.AddRange(validators);
            }
            return this;
        }

        public QuestionDialogPartBuilder AddValidators(System.Collections.Generic.IEnumerable<DialogFramework.Core.DomainModel.Builders.QuestionDialogPartValidatorBuilder> validators)
        {
            return AddValidators(validators.ToArray());
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IQuestionDialogPart Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.Core.DomainModel.DialogParts.QuestionDialogPart(Title, Results.Select(x => x.Build()), Validators.Select(x => x.Build()), ValidationErrors.Select(x => x.Build()), Group?.Build(), Heading, Id);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public QuestionDialogPartBuilder WithGroup(DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder group)
        {
            Group = group;
            return this;
        }

        public QuestionDialogPartBuilder WithGroup(System.Func<DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder> groupDelegate)
        {
            _groupDelegate = new (groupDelegate);
            return this;
        }

        public QuestionDialogPartBuilder WithHeading(System.Func<string> headingDelegate)
        {
            _headingDelegate = new (headingDelegate);
            return this;
        }

        public QuestionDialogPartBuilder WithHeading(string heading)
        {
            Heading = heading;
            return this;
        }

        public QuestionDialogPartBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public QuestionDialogPartBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public QuestionDialogPartBuilder WithTitle(System.Func<string> titleDelegate)
        {
            _titleDelegate = new (titleDelegate);
            return this;
        }

        public QuestionDialogPartBuilder WithTitle(string title)
        {
            Title = title;
            return this;
        }

        public QuestionDialogPartBuilder()
        {
            Results = new System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DialogPartResultDefinitionBuilder>();
            Validators = new System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.QuestionDialogPartValidatorBuilder>();
            ValidationErrors = new System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DialogValidationResultBuilder>();
            #pragma warning disable CS8603 // Possible null reference return.
            _titleDelegate = new (() => string.Empty);
            _groupDelegate = new (() => default);
            _headingDelegate = new (() => string.Empty);
            _idDelegate = new (() => string.Empty);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public QuestionDialogPartBuilder(DialogFramework.Abstractions.DomainModel.DialogParts.IQuestionDialogPart source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            Results = new System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DialogPartResultDefinitionBuilder>();
            Validators = new System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.QuestionDialogPartValidatorBuilder>();
            ValidationErrors = new System.Collections.Generic.List<DialogFramework.Core.DomainModel.Builders.DialogValidationResultBuilder>();
            _titleDelegate = new (() => source.Title);
            if (source.Results != null) Results.AddRange(source.Results.Select(x => new DialogFramework.Core.DomainModel.Builders.DialogPartResultDefinitionBuilder(x)));
            if (source.Validators != null) Validators.AddRange(source.Validators.Select(x => new DialogFramework.Core.DomainModel.Builders.QuestionDialogPartValidatorBuilder(x)));
            if (source.ValidationErrors != null) ValidationErrors.AddRange(source.ValidationErrors.Select(x => new DialogFramework.Core.DomainModel.Builders.DialogValidationResultBuilder(x)));
            _groupDelegate = new(() => new DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder(source.Group));
            _headingDelegate = new (() => source.Heading);
            _idDelegate = new (() => source.Id);
        }

        private System.Lazy<string> _titleDelegate;

        private System.Lazy<DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder> _groupDelegate;

        private System.Lazy<string> _headingDelegate;

        private System.Lazy<string> _idDelegate;
    }
#nullable restore
}

