// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.DialogParts.Builders
{
#nullable enable
    public partial class RedirectDialogPartBuilder
    {
        public DialogFramework.Core.DomainModel.Builders.DialogMetadataBuilder RedirectDialogMetadata
        {
            get
            {
                return _redirectDialogMetadataDelegate.Value;
            }
            set
            {
                _redirectDialogMetadataDelegate = new (() => value);
            }
        }

        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IRedirectDialogPart Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.Core.DomainModel.DialogParts.RedirectDialogPart(RedirectDialogMetadata?.Build(), Id);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public RedirectDialogPartBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public RedirectDialogPartBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public RedirectDialogPartBuilder WithRedirectDialogMetadata(DialogFramework.Core.DomainModel.Builders.DialogMetadataBuilder redirectDialogMetadata)
        {
            RedirectDialogMetadata = redirectDialogMetadata;
            return this;
        }

        public RedirectDialogPartBuilder WithRedirectDialogMetadata(System.Func<DialogFramework.Core.DomainModel.Builders.DialogMetadataBuilder> redirectDialogMetadataDelegate)
        {
            _redirectDialogMetadataDelegate = new (redirectDialogMetadataDelegate);
            return this;
        }

        public RedirectDialogPartBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _redirectDialogMetadataDelegate = new (() => default);
            _idDelegate = new (() => string.Empty);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public RedirectDialogPartBuilder(DialogFramework.Abstractions.DomainModel.DialogParts.IRedirectDialogPart source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _redirectDialogMetadataDelegate = new(() => new DialogFramework.Core.DomainModel.Builders.DialogMetadataBuilder(source.RedirectDialogMetadata));
            _idDelegate = new (() => source.Id);
        }

        private System.Lazy<DialogFramework.Core.DomainModel.Builders.DialogMetadataBuilder> _redirectDialogMetadataDelegate;

        private System.Lazy<string> _idDelegate;
    }
#nullable restore
}

