// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.Builders
{
#nullable enable
    public partial class DecisionBuilder
    {
        public System.Collections.Generic.List<ExpressionFramework.Core.DomainModel.Builders.ConditionBuilder> Conditions
        {
            get;
            set;
        }

        public string NextPartId
        {
            get
            {
                return _nextPartIdDelegate.Value;
            }
            set
            {
                _nextPartIdDelegate = new (() => value);
            }
        }

        public DecisionBuilder AddConditions(params ExpressionFramework.Core.DomainModel.Builders.ConditionBuilder[] conditions)
        {
            if (conditions != null)
            {
                Conditions.AddRange(conditions);
            }
            return this;
        }

        public DecisionBuilder AddConditions(System.Collections.Generic.IEnumerable<ExpressionFramework.Core.DomainModel.Builders.ConditionBuilder> conditions)
        {
            return AddConditions(conditions.ToArray());
        }

        public DialogFramework.Abstractions.DomainModel.IDecision Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.Decision(Conditions.Select(x => x.Build()), NextPartId);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DecisionBuilder WithNextPartId(System.Func<string> nextPartIdDelegate)
        {
            _nextPartIdDelegate = new (nextPartIdDelegate);
            return this;
        }

        public DecisionBuilder WithNextPartId(string nextPartId)
        {
            NextPartId = nextPartId;
            return this;
        }

        public DecisionBuilder()
        {
            Conditions = new System.Collections.Generic.List<ExpressionFramework.Core.DomainModel.Builders.ConditionBuilder>();
            #pragma warning disable CS8603 // Possible null reference return.
            _nextPartIdDelegate = new (() => string.Empty);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DecisionBuilder(DialogFramework.Abstractions.DomainModel.IDecision source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            Conditions = new System.Collections.Generic.List<ExpressionFramework.Core.DomainModel.Builders.ConditionBuilder>();
            if (source.Conditions != null) Conditions.AddRange(source.Conditions.Select(x => new ExpressionFramework.Core.DomainModel.Builders.ConditionBuilder(x)));
            _nextPartIdDelegate = new (() => source.NextPartId);
        }

        private System.Lazy<string> _nextPartIdDelegate;
    }
#nullable restore
}

