// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.Builders
{
#nullable enable
    public partial class DialogPartResultValueBuilder
    {
        public object? Value
        {
            get
            {
                return _valueDelegate.Value;
            }
            set
            {
                _valueDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.Domains.ResultValueType ResultValueType
        {
            get
            {
                return _resultValueTypeDelegate.Value;
            }
            set
            {
                _resultValueTypeDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.IDialogPartResultValue Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.DialogPartResultValue(Value, ResultValueType);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DialogPartResultValueBuilder WithResultValueType(DialogFramework.Abstractions.DomainModel.Domains.ResultValueType resultValueType)
        {
            ResultValueType = resultValueType;
            return this;
        }

        public DialogPartResultValueBuilder WithResultValueType(System.Func<DialogFramework.Abstractions.DomainModel.Domains.ResultValueType> resultValueTypeDelegate)
        {
            _resultValueTypeDelegate = new (resultValueTypeDelegate);
            return this;
        }

        public DialogPartResultValueBuilder WithValue(System.Func<object?> valueDelegate)
        {
            _valueDelegate = new (valueDelegate);
            return this;
        }

        public DialogPartResultValueBuilder WithValue(object? value)
        {
            Value = value;
            return this;
        }

        public DialogPartResultValueBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _valueDelegate = new (() => default);
            _resultValueTypeDelegate = new (() => default);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DialogPartResultValueBuilder(DialogFramework.Abstractions.DomainModel.IDialogPartResultValue source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _valueDelegate = new (() => source.Value);
            _resultValueTypeDelegate = new (() => source.ResultValueType);
        }

        private System.Lazy<object?> _valueDelegate;

        private System.Lazy<DialogFramework.Abstractions.DomainModel.Domains.ResultValueType> _resultValueTypeDelegate;
    }
#nullable restore
}

