// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.Builders
{
#nullable enable
    public partial class DialogMetadataBuilder
    {
        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public string FriendlyName
        {
            get
            {
                return _friendlyNameDelegate.Value;
            }
            set
            {
                _friendlyNameDelegate = new (() => value);
            }
        }

        public string Version
        {
            get
            {
                return _versionDelegate.Value;
            }
            set
            {
                _versionDelegate = new (() => value);
            }
        }

        public bool CanStart
        {
            get
            {
                return _canStartDelegate.Value;
            }
            set
            {
                _canStartDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.IDialogMetadata Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.DialogMetadata(Id, FriendlyName, Version, CanStart);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DialogMetadataBuilder WithCanStart(bool canStart = true)
        {
            CanStart = canStart;
            return this;
        }

        public DialogMetadataBuilder WithCanStart(System.Func<bool> canStartDelegate)
        {
            _canStartDelegate = new (canStartDelegate);
            return this;
        }

        public DialogMetadataBuilder WithFriendlyName(System.Func<string> friendlyNameDelegate)
        {
            _friendlyNameDelegate = new (friendlyNameDelegate);
            return this;
        }

        public DialogMetadataBuilder WithFriendlyName(string friendlyName)
        {
            FriendlyName = friendlyName;
            return this;
        }

        public DialogMetadataBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public DialogMetadataBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public DialogMetadataBuilder WithVersion(System.Func<string> versionDelegate)
        {
            _versionDelegate = new (versionDelegate);
            return this;
        }

        public DialogMetadataBuilder WithVersion(string version)
        {
            Version = version;
            return this;
        }

        public DialogMetadataBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _idDelegate = new (() => string.Empty);
            _friendlyNameDelegate = new (() => string.Empty);
            _versionDelegate = new (() => string.Empty);
            _canStartDelegate = new (() => true);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DialogMetadataBuilder(DialogFramework.Abstractions.DomainModel.IDialogMetadata source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _idDelegate = new (() => source.Id);
            _friendlyNameDelegate = new (() => source.FriendlyName);
            _versionDelegate = new (() => source.Version);
            _canStartDelegate = new (() => source.CanStart);
        }

        private System.Lazy<string> _idDelegate;

        private System.Lazy<string> _friendlyNameDelegate;

        private System.Lazy<string> _versionDelegate;

        private System.Lazy<bool> _canStartDelegate;
    }
#nullable restore
}

