// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.Builders
{
#nullable enable
    public partial class DialogPartResultDefinitionBuilder
    {
        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public string Title
        {
            get
            {
                return _titleDelegate.Value;
            }
            set
            {
                _titleDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.Domains.ResultValueType ValueType
        {
            get
            {
                return _valueTypeDelegate.Value;
            }
            set
            {
                _valueTypeDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<DialogFramework.UniversalModel.DomainModel.Builders.DialogPartResultDefinitionValidatorBuilder> Validators
        {
            get;
            set;
        }

        public DialogPartResultDefinitionBuilder AddValidators(params DialogFramework.UniversalModel.DomainModel.Builders.DialogPartResultDefinitionValidatorBuilder[] validators)
        {
            if (validators != null)
            {
                Validators.AddRange(validators);
            }
            return this;
        }

        public DialogPartResultDefinitionBuilder AddValidators(System.Collections.Generic.IEnumerable<DialogFramework.UniversalModel.DomainModel.Builders.DialogPartResultDefinitionValidatorBuilder> validators)
        {
            return AddValidators(validators.ToArray());
        }

        public DialogFramework.Abstractions.DomainModel.IDialogPartResultDefinition Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.DialogPartResultDefinition(Id, Title, ValueType, Validators.Select(x => x.Build()));
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DialogPartResultDefinitionBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public DialogPartResultDefinitionBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public DialogPartResultDefinitionBuilder WithTitle(System.Func<string> titleDelegate)
        {
            _titleDelegate = new (titleDelegate);
            return this;
        }

        public DialogPartResultDefinitionBuilder WithTitle(string title)
        {
            Title = title;
            return this;
        }

        public DialogPartResultDefinitionBuilder WithValueType(DialogFramework.Abstractions.DomainModel.Domains.ResultValueType valueType)
        {
            ValueType = valueType;
            return this;
        }

        public DialogPartResultDefinitionBuilder WithValueType(System.Func<DialogFramework.Abstractions.DomainModel.Domains.ResultValueType> valueTypeDelegate)
        {
            _valueTypeDelegate = new (valueTypeDelegate);
            return this;
        }

        public DialogPartResultDefinitionBuilder()
        {
            Validators = new System.Collections.Generic.List<DialogFramework.UniversalModel.DomainModel.Builders.DialogPartResultDefinitionValidatorBuilder>();
            #pragma warning disable CS8603 // Possible null reference return.
            _idDelegate = new (() => string.Empty);
            _titleDelegate = new (() => string.Empty);
            _valueTypeDelegate = new (() => default);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DialogPartResultDefinitionBuilder(DialogFramework.Abstractions.DomainModel.IDialogPartResultDefinition source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            Validators = new System.Collections.Generic.List<DialogFramework.UniversalModel.DomainModel.Builders.DialogPartResultDefinitionValidatorBuilder>();
            _idDelegate = new (() => source.Id);
            _titleDelegate = new (() => source.Title);
            _valueTypeDelegate = new (() => source.ValueType);
            if (source.Validators != null) Validators.AddRange(source.Validators.Select(x => new DialogFramework.UniversalModel.DomainModel.Builders.DialogPartResultDefinitionValidatorBuilder(x)));
        }

        private System.Lazy<string> _idDelegate;

        private System.Lazy<string> _titleDelegate;

        private System.Lazy<DialogFramework.Abstractions.DomainModel.Domains.ResultValueType> _valueTypeDelegate;
    }
#nullable restore
}

