// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel.Builders
{
#nullable enable
    public partial class DialogIdentifierBuilder
    {
        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public string Version
        {
            get
            {
                return _versionDelegate.Value;
            }
            set
            {
                _versionDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.IDialogIdentifier Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.UniversalModel.DomainModel.DialogIdentifier(Id, Version);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DialogIdentifierBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public DialogIdentifierBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public DialogIdentifierBuilder WithVersion(System.Func<string> versionDelegate)
        {
            _versionDelegate = new (versionDelegate);
            return this;
        }

        public DialogIdentifierBuilder WithVersion(string version)
        {
            Version = version;
            return this;
        }

        public DialogIdentifierBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _idDelegate = new (() => string.Empty);
            _versionDelegate = new (() => string.Empty);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DialogIdentifierBuilder(DialogFramework.Abstractions.DomainModel.IDialogIdentifier source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _idDelegate = new (() => source.Id);
            _versionDelegate = new (() => source.Version);
        }

        private System.Lazy<string> _idDelegate;

        private System.Lazy<string> _versionDelegate;
    }
#nullable restore
}

