// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using ModelFramework.Objects.Builders;
using ModelFramework.Objects.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CodeGeneration.CodeGenerationProviders
{
#nullable enable
    public partial class DialogFrameworkCSharpClassBase
    {
        protected static ITypeBase[] GetDialogPartModels()
        {
            return new[]
            {
                new ClassBuilder()
                    .WithNamespace(@"DialogFramework.Abstractions.DialogParts")
                    .AddInterfaces(
                        @"DialogFramework.Abstractions.IDialogPart")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Message")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Id")
                            .WithTypeName(@"System.String"))
                    .AddMethods(
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetState")
                            .WithTypeName(@"DialogFramework.Abstractions.DialogState"))
                    .WithName(@"IAbortedDialogPart"),
                new ClassBuilder()
                    .WithNamespace(@"DialogFramework.Abstractions.DialogParts")
                    .AddInterfaces(
                        @"DialogFramework.Abstractions.DialogParts.IGroupedDialogPart",
                        @"DialogFramework.Abstractions.IDialogPart")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Message")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Group")
                            .WithTypeName(@"DialogFramework.Abstractions.IDialogPartGroup"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Heading")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Id")
                            .WithTypeName(@"System.String"))
                    .AddMethods(
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetState")
                            .WithTypeName(@"DialogFramework.Abstractions.DialogState"))
                    .WithName(@"ICompletedDialogPart"),
                new ClassBuilder()
                    .WithNamespace(@"DialogFramework.Abstractions.DialogParts")
                    .AddInterfaces(
                        @"DialogFramework.Abstractions.IDialogPart")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Id")
                            .WithTypeName(@"System.String"))
                    .AddMethods(
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetNextPartId")
                            .AddParameters(
                                new ParameterBuilder()
                                    .WithTypeName(@"DialogFramework.Abstractions.IDialogContext")
                                    .WithName(@"context"),
                                new ParameterBuilder()
                                    .WithTypeName(@"DialogFramework.Abstractions.IDialog")
                                    .WithName(@"dialog"),
                                new ParameterBuilder()
                                    .WithTypeName(@"ExpressionFramework.Abstractions.IConditionEvaluator")
                                    .WithName(@"conditionEvaluator"))
                            .WithTypeName(@"System.String"),
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetState")
                            .WithTypeName(@"DialogFramework.Abstractions.DialogState"))
                    .WithName(@"IDecisionDialogPart"),
                new ClassBuilder()
                    .WithNamespace(@"DialogFramework.Abstractions.DialogParts")
                    .AddInterfaces(
                        @"DialogFramework.Abstractions.IDialogPart")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ErrorMessage")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Id")
                            .WithTypeName(@"System.String"))
                    .AddMethods(
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetState")
                            .WithTypeName(@"DialogFramework.Abstractions.DialogState"))
                    .WithName(@"IErrorDialogPart"),
                new ClassBuilder()
                    .WithNamespace(@"DialogFramework.Abstractions.DialogParts")
                    .AddInterfaces(
                        @"DialogFramework.Abstractions.DialogParts.IGroupedDialogPart",
                        @"DialogFramework.Abstractions.IDialogPart")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Message")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Group")
                            .WithTypeName(@"DialogFramework.Abstractions.IDialogPartGroup"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Heading")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Id")
                            .WithTypeName(@"System.String"))
                    .AddMethods(
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetState")
                            .WithTypeName(@"DialogFramework.Abstractions.DialogState"))
                    .WithName(@"IMessageDialogPart"),
                new ClassBuilder()
                    .WithNamespace(@"DialogFramework.Abstractions.DialogParts")
                    .AddInterfaces(
                        @"DialogFramework.Abstractions.IDialogPart")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Id")
                            .WithTypeName(@"System.String"))
                    .AddMethods(
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetNextPartId")
                            .AddParameters(
                                new ParameterBuilder()
                                    .WithTypeName(@"DialogFramework.Abstractions.IDialogContext")
                                    .WithName(@"context"))
                            .WithTypeName(@"System.String"),
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetState")
                            .WithTypeName(@"DialogFramework.Abstractions.DialogState"))
                    .WithName(@"INavigationDialogPart"),
                new ClassBuilder()
                    .WithNamespace(@"DialogFramework.Abstractions.DialogParts")
                    .AddInterfaces(
                        @"DialogFramework.Abstractions.DialogParts.IGroupedDialogPart",
                        @"DialogFramework.Abstractions.IDialogPart")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Title")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Results")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[DialogFramework.Abstractions.IDialogPartResultDefinition, DialogFramework.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Validators")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[DialogFramework.Abstractions.IQuestionDialogPartValidator, DialogFramework.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"ValidationErrors")
                            .WithTypeName(@"System.Collections.Generic.IReadOnlyCollection`1[[DialogFramework.Abstractions.IDialogValidationResult, DialogFramework.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Group")
                            .WithTypeName(@"DialogFramework.Abstractions.IDialogPartGroup"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Heading")
                            .WithTypeName(@"System.String"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Id")
                            .WithTypeName(@"System.String"))
                    .AddMethods(
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"Validate")
                            .AddParameters(
                                new ParameterBuilder()
                                    .WithTypeName(@"DialogFramework.Abstractions.IDialogContext")
                                    .WithName(@"context"),
                                new ParameterBuilder()
                                    .WithTypeName(@"DialogFramework.Abstractions.IDialog")
                                    .WithName(@"dialog"),
                                new ParameterBuilder()
                                    .WithTypeName(@"System.Collections.Generic.IEnumerable<DialogFramework.Abstractions.IDialogPartResult>")
                                    .WithName(@"dialogPartResults"))
                            .WithTypeName(@"DialogFramework.Abstractions.IDialogPart"),
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetState")
                            .WithTypeName(@"DialogFramework.Abstractions.DialogState"))
                    .WithName(@"IQuestionDialogPart"),
                new ClassBuilder()
                    .WithNamespace(@"DialogFramework.Abstractions.DialogParts")
                    .AddInterfaces(
                        @"DialogFramework.Abstractions.IDialogPart")
                    .AddProperties(
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"RedirectDialogMetadata")
                            .WithTypeName(@"DialogFramework.Abstractions.IDialogMetadata"),
                        new ClassPropertyBuilder()
                            .WithHasSetter(false)
                            .WithName(@"Id")
                            .WithTypeName(@"System.String"))
                    .AddMethods(
                        new ClassMethodBuilder()
                            .WithVirtual(true)
                            .WithAbstract(true)
                            .WithName(@"GetState")
                            .WithTypeName(@"DialogFramework.Abstractions.DialogState"))
                    .WithName(@"IRedirectDialogPart"),
            }.Select(x => x.Build()).ToArray();
        }
    }
#nullable restore
}
