// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel
{
#nullable enable
    public partial record Decision : DialogFramework.Abstractions.DomainModel.IDecision
    {
        public CrossCutting.Common.ValueCollection<ExpressionFramework.Abstractions.DomainModel.ICondition> Conditions
        {
            get;
        }

        public string NextPartId
        {
            get;
        }

        public Decision(System.Collections.Generic.IEnumerable<ExpressionFramework.Abstractions.DomainModel.ICondition> conditions, string nextPartId)
        {
            if (conditions == null) throw new System.ArgumentNullException("conditions");
            this.Conditions = new CrossCutting.Common.ValueCollection<ExpressionFramework.Abstractions.DomainModel.ICondition>(conditions);
            this.NextPartId = nextPartId;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

