// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.UniversalModel.DomainModel
{
#nullable enable
    public partial record Dialog : DialogFramework.Abstractions.DomainModel.IDialog
    {
        public DialogFramework.Abstractions.DomainModel.IDialogMetadata Metadata
        {
            get;
        }

        public CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPart> Parts
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IErrorDialogPart ErrorPart
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.IAbortedDialogPart AbortedPart
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.DialogParts.ICompletedDialogPart CompletedPart
        {
            get;
        }

        public CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPartGroup> PartGroups
        {
            get;
        }

        public Dialog(DialogFramework.Abstractions.DomainModel.IDialogMetadata metadata, System.Collections.Generic.IEnumerable<DialogFramework.Abstractions.DomainModel.IDialogPart> parts, DialogFramework.Abstractions.DomainModel.DialogParts.IErrorDialogPart errorPart, DialogFramework.Abstractions.DomainModel.DialogParts.IAbortedDialogPart abortedPart, DialogFramework.Abstractions.DomainModel.DialogParts.ICompletedDialogPart completedPart, System.Collections.Generic.IEnumerable<DialogFramework.Abstractions.DomainModel.IDialogPartGroup> partGroups)
        {
            if (metadata == null) throw new System.ArgumentNullException("metadata");
            if (parts == null) throw new System.ArgumentNullException("parts");
            if (errorPart == null) throw new System.ArgumentNullException("errorPart");
            if (abortedPart == null) throw new System.ArgumentNullException("abortedPart");
            if (completedPart == null) throw new System.ArgumentNullException("completedPart");
            if (partGroups == null) throw new System.ArgumentNullException("partGroups");
            this.Metadata = metadata;
            this.Parts = new CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPart>(parts);
            this.ErrorPart = errorPart;
            this.AbortedPart = abortedPart;
            this.CompletedPart = completedPart;
            this.PartGroups = new CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPartGroup>(partGroups);
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

