// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel
{
#nullable enable
    public partial record DialogValidationResult : DialogFramework.Abstractions.DomainModel.IDialogValidationResult
    {
        public string ErrorMessage
        {
            get;
        }

        public CrossCutting.Common.ValueCollection<string> DialogPartResultIds
        {
            get;
        }

        public DialogValidationResult(string errorMessage, CrossCutting.Common.ValueCollection<string> dialogPartResultIds)
        {
            if (dialogPartResultIds == null) throw new System.ArgumentNullException("dialogPartResultIds");
            this.ErrorMessage = errorMessage;
            this.DialogPartResultIds = dialogPartResultIds;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

