// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel
{
#nullable enable
    public partial record DialogPartResult : DialogFramework.Abstractions.DomainModel.IDialogPartResult
    {
        public string DialogPartId
        {
            get;
        }

        public string ResultId
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.IDialogPartResultValue Value
        {
            get;
        }

        public DialogPartResult(string dialogPartId, string resultId, DialogFramework.Abstractions.DomainModel.IDialogPartResultValue value)
        {
            if (value == null) throw new System.ArgumentNullException("value");
            this.DialogPartId = dialogPartId;
            this.ResultId = resultId;
            this.Value = value;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

