// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel
{
#nullable enable
    public partial record DialogPartGroup : DialogFramework.Abstractions.DomainModel.IDialogPartGroup
    {
        public string Id
        {
            get;
        }

        public string Title
        {
            get;
        }

        public int Number
        {
            get;
        }

        public DialogPartGroup(string id, string title, int number)
        {
            this.Id = id;
            this.Title = title;
            this.Number = number;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

