// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel
{
#nullable enable
    public partial record DialogPartResultValue : DialogFramework.Abstractions.DomainModel.IDialogPartResultValue
    {
        public object? Value
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.Domains.ResultValueType ResultValueType
        {
            get;
        }

        public DialogPartResultValue(object? value, DialogFramework.Abstractions.DomainModel.Domains.ResultValueType resultValueType)
        {
            this.Value = value;
            this.ResultValueType = resultValueType;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

