// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel
{
#nullable enable
    public partial record DialogPartResultDefinition : DialogFramework.Abstractions.DomainModel.IDialogPartResultDefinition
    {
        public string Id
        {
            get;
        }

        public string Title
        {
            get;
        }

        public DialogFramework.Abstractions.DomainModel.Domains.ResultValueType ValueType
        {
            get;
        }

        public CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPartResultDefinitionValidator> Validators
        {
            get;
        }

        public DialogPartResultDefinition(string id, string title, DialogFramework.Abstractions.DomainModel.Domains.ResultValueType valueType, System.Collections.Generic.IEnumerable<DialogFramework.Abstractions.DomainModel.IDialogPartResultDefinitionValidator> validators)
        {
            if (validators == null) throw new System.ArgumentNullException("validators");
            this.Id = id;
            this.Title = title;
            this.ValueType = valueType;
            this.Validators = new CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPartResultDefinitionValidator>(validators);
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

