// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.Builders
{
#nullable enable
    public partial class DialogContextBuilder
    {
        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public DialogFramework.Core.DomainModel.Builders.DialogIdentifierBuilder CurrentDialogIdentifier
        {
            get
            {
                return _currentDialogIdentifierDelegate.Value;
            }
            set
            {
                _currentDialogIdentifierDelegate = new (() => value);
            }
        }

        public DialogFramework.Core.DomainModel.Builders.DialogPartBuilder CurrentPart
        {
            get
            {
                return _currentPartDelegate.Value;
            }
            set
            {
                _currentPartDelegate = new (() => value);
            }
        }

        public DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder? CurrentGroup
        {
            get
            {
                return _currentGroupDelegate.Value;
            }
            set
            {
                _currentGroupDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.Domains.DialogState CurrentState
        {
            get
            {
                return _currentStateDelegate.Value;
            }
            set
            {
                _currentStateDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<DialogFramework.Abstractions.DomainModel.IDialogPartResult> Answers
        {
            get;
            set;
        }

        public System.Exception? Exception
        {
            get
            {
                return _exceptionDelegate.Value;
            }
            set
            {
                _exceptionDelegate = new (() => value);
            }
        }

        public DialogContextBuilder AddAnswers(params DialogFramework.Abstractions.DomainModel.IDialogPartResult[] answers)
        {
            if (answers != null)
            {
                Answers.AddRange(answers);
            }
            return this;
        }

        public DialogContextBuilder AddAnswers(System.Collections.Generic.IEnumerable<DialogFramework.Abstractions.DomainModel.IDialogPartResult> answers)
        {
            return AddAnswers(answers.ToArray());
        }

        public DialogFramework.Abstractions.IDialogContext Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.Core.DialogContext(Id, CurrentDialogIdentifier?.Build(), CurrentPart?.Build(), CurrentGroup?.Build(), CurrentState, new CrossCutting.Common.ValueCollection<DialogFramework.Abstractions.DomainModel.IDialogPartResult>(Answers), Exception);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DialogContextBuilder WithCurrentDialogIdentifier(DialogFramework.Core.DomainModel.Builders.DialogIdentifierBuilder currentDialogIdentifier)
        {
            CurrentDialogIdentifier = currentDialogIdentifier;
            return this;
        }

        public DialogContextBuilder WithCurrentDialogIdentifier(System.Func<DialogFramework.Core.DomainModel.Builders.DialogIdentifierBuilder> currentDialogIdentifierDelegate)
        {
            _currentDialogIdentifierDelegate = new (currentDialogIdentifierDelegate);
            return this;
        }

        public DialogContextBuilder WithCurrentGroup(DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder? currentGroup)
        {
            CurrentGroup = currentGroup;
            return this;
        }

        public DialogContextBuilder WithCurrentGroup(System.Func<DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder?> currentGroupDelegate)
        {
            _currentGroupDelegate = new (currentGroupDelegate);
            return this;
        }

        public DialogContextBuilder WithCurrentPart(DialogFramework.Core.DomainModel.Builders.DialogPartBuilder currentPart)
        {
            CurrentPart = currentPart;
            return this;
        }

        public DialogContextBuilder WithCurrentPart(System.Func<DialogFramework.Core.DomainModel.Builders.DialogPartBuilder> currentPartDelegate)
        {
            _currentPartDelegate = new (currentPartDelegate);
            return this;
        }

        public DialogContextBuilder WithCurrentState(DialogFramework.Abstractions.DomainModel.Domains.DialogState currentState)
        {
            CurrentState = currentState;
            return this;
        }

        public DialogContextBuilder WithCurrentState(System.Func<DialogFramework.Abstractions.DomainModel.Domains.DialogState> currentStateDelegate)
        {
            _currentStateDelegate = new (currentStateDelegate);
            return this;
        }

        public DialogContextBuilder WithException(System.Exception? exception)
        {
            Exception = exception;
            return this;
        }

        public DialogContextBuilder WithException(System.Func<System.Exception?> exceptionDelegate)
        {
            _exceptionDelegate = new (exceptionDelegate);
            return this;
        }

        public DialogContextBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public DialogContextBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public DialogContextBuilder()
        {
            Answers = new System.Collections.Generic.List<DialogFramework.Abstractions.DomainModel.IDialogPartResult>();
            #pragma warning disable CS8603 // Possible null reference return.
            _idDelegate = new (() => string.Empty);
            _currentDialogIdentifierDelegate = new (() => default);
            _currentPartDelegate = new (() => default);
            _currentGroupDelegate = new (() => default);
            _currentStateDelegate = new (() => default);
            _exceptionDelegate = new (() => default);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DialogContextBuilder(DialogFramework.Abstractions.IDialogContext source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            Answers = new System.Collections.Generic.List<DialogFramework.Abstractions.DomainModel.IDialogPartResult>();
            _idDelegate = new (() => source.Id);
            _currentDialogIdentifierDelegate = new(() => new DialogFramework.Core.DomainModel.Builders.DialogIdentifierBuilder(source.CurrentDialogIdentifier));
            _currentPartDelegate = new(() => new DialogFramework.Core.DomainModel.Builders.DialogPartBuilder(source.CurrentPart));
            _currentGroupDelegate = new(() => source.CurrentGroup == null ? default : new DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder(source.CurrentGroup));
            _currentStateDelegate = new (() => source.CurrentState);
            // skip: Answers;
            _exceptionDelegate = new (() => default);
        }

        private System.Lazy<string> _idDelegate;

        private System.Lazy<DialogFramework.Core.DomainModel.Builders.DialogIdentifierBuilder> _currentDialogIdentifierDelegate;

        private System.Lazy<DialogFramework.Core.DomainModel.Builders.DialogPartBuilder> _currentPartDelegate;

        private System.Lazy<DialogFramework.Core.DomainModel.Builders.DialogPartGroupBuilder?> _currentGroupDelegate;

        private System.Lazy<DialogFramework.Abstractions.DomainModel.Domains.DialogState> _currentStateDelegate;

        private System.Lazy<System.Exception?> _exceptionDelegate;
    }
#nullable restore
}

