// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.Builders
{
#nullable enable
    public partial class DialogPartGroupBuilder
    {
        public string Id
        {
            get
            {
                return _idDelegate.Value;
            }
            set
            {
                _idDelegate = new (() => value);
            }
        }

        public string Title
        {
            get
            {
                return _titleDelegate.Value;
            }
            set
            {
                _titleDelegate = new (() => value);
            }
        }

        public int Number
        {
            get
            {
                return _numberDelegate.Value;
            }
            set
            {
                _numberDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.IDialogPartGroup Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.Core.DomainModel.DialogPartGroup(Id, Title, Number);
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DialogPartGroupBuilder WithId(System.Func<string> idDelegate)
        {
            _idDelegate = new (idDelegate);
            return this;
        }

        public DialogPartGroupBuilder WithId(string id)
        {
            Id = id;
            return this;
        }

        public DialogPartGroupBuilder WithNumber(System.Func<int> numberDelegate)
        {
            _numberDelegate = new (numberDelegate);
            return this;
        }

        public DialogPartGroupBuilder WithNumber(int number)
        {
            Number = number;
            return this;
        }

        public DialogPartGroupBuilder WithTitle(System.Func<string> titleDelegate)
        {
            _titleDelegate = new (titleDelegate);
            return this;
        }

        public DialogPartGroupBuilder WithTitle(string title)
        {
            Title = title;
            return this;
        }

        public DialogPartGroupBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _idDelegate = new (() => string.Empty);
            _titleDelegate = new (() => string.Empty);
            _numberDelegate = new (() => default);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DialogPartGroupBuilder(DialogFramework.Abstractions.DomainModel.IDialogPartGroup source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _idDelegate = new (() => source.Id);
            _titleDelegate = new (() => source.Title);
            _numberDelegate = new (() => source.Number);
        }

        private System.Lazy<string> _idDelegate;

        private System.Lazy<string> _titleDelegate;

        private System.Lazy<int> _numberDelegate;
    }
#nullable restore
}

