// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.Builders
{
#nullable enable
    public partial class DialogPartResultBuilder
    {
        public string DialogPartId
        {
            get
            {
                return _dialogPartIdDelegate.Value;
            }
            set
            {
                _dialogPartIdDelegate = new (() => value);
            }
        }

        public string ResultId
        {
            get
            {
                return _resultIdDelegate.Value;
            }
            set
            {
                _resultIdDelegate = new (() => value);
            }
        }

        public DialogFramework.Core.DomainModel.Builders.DialogPartResultValueBuilder Value
        {
            get
            {
                return _valueDelegate.Value;
            }
            set
            {
                _valueDelegate = new (() => value);
            }
        }

        public DialogFramework.Abstractions.DomainModel.IDialogPartResult Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.Core.DomainModel.DialogPartResult(DialogPartId, ResultId, Value?.Build());
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DialogPartResultBuilder WithDialogPartId(System.Func<string> dialogPartIdDelegate)
        {
            _dialogPartIdDelegate = new (dialogPartIdDelegate);
            return this;
        }

        public DialogPartResultBuilder WithDialogPartId(string dialogPartId)
        {
            DialogPartId = dialogPartId;
            return this;
        }

        public DialogPartResultBuilder WithResultId(System.Func<string> resultIdDelegate)
        {
            _resultIdDelegate = new (resultIdDelegate);
            return this;
        }

        public DialogPartResultBuilder WithResultId(string resultId)
        {
            ResultId = resultId;
            return this;
        }

        public DialogPartResultBuilder WithValue(DialogFramework.Core.DomainModel.Builders.DialogPartResultValueBuilder value)
        {
            Value = value;
            return this;
        }

        public DialogPartResultBuilder WithValue(System.Func<DialogFramework.Core.DomainModel.Builders.DialogPartResultValueBuilder> valueDelegate)
        {
            _valueDelegate = new (valueDelegate);
            return this;
        }

        public DialogPartResultBuilder()
        {
            #pragma warning disable CS8603 // Possible null reference return.
            _dialogPartIdDelegate = new (() => string.Empty);
            _resultIdDelegate = new (() => string.Empty);
            _valueDelegate = new (() => new DialogFramework.Core.DomainModel.DialogPartResultValues.Builders.EmptyDialogPartResultValueBuilder());
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DialogPartResultBuilder(DialogFramework.Abstractions.DomainModel.IDialogPartResult source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            _dialogPartIdDelegate = new (() => source.DialogPartId);
            _resultIdDelegate = new (() => source.ResultId);
            _valueDelegate = new(() => new DialogFramework.Core.DomainModel.Builders.DialogPartResultValueBuilder(source.Value));
        }

        private System.Lazy<string> _dialogPartIdDelegate;

        private System.Lazy<string> _resultIdDelegate;

        private System.Lazy<DialogFramework.Core.DomainModel.Builders.DialogPartResultValueBuilder> _valueDelegate;
    }
#nullable restore
}

