// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DialogFramework.Core.DomainModel.Builders
{
#nullable enable
    public partial class DialogValidationResultBuilder
    {
        public string ErrorMessage
        {
            get
            {
                return _errorMessageDelegate.Value;
            }
            set
            {
                _errorMessageDelegate = new (() => value);
            }
        }

        public System.Collections.Generic.List<string> DialogPartResultIds
        {
            get;
            set;
        }

        public DialogValidationResultBuilder AddDialogPartResultIds(System.Collections.Generic.IEnumerable<string> dialogPartResultIds)
        {
            return AddDialogPartResultIds(dialogPartResultIds.ToArray());
        }

        public DialogValidationResultBuilder AddDialogPartResultIds(params string[] dialogPartResultIds)
        {
            if (dialogPartResultIds != null)
            {
                DialogPartResultIds.AddRange(dialogPartResultIds);
            }
            return this;
        }

        public DialogFramework.Abstractions.DomainModel.IDialogValidationResult Build()
        {
            #pragma warning disable CS8604 // Possible null reference argument.
            return new DialogFramework.Core.DomainModel.DialogValidationResult(ErrorMessage, new CrossCutting.Common.ValueCollection<System.String>(DialogPartResultIds));
            #pragma warning restore CS8604 // Possible null reference argument.
        }

        public DialogValidationResultBuilder WithErrorMessage(System.Func<string> errorMessageDelegate)
        {
            _errorMessageDelegate = new (errorMessageDelegate);
            return this;
        }

        public DialogValidationResultBuilder WithErrorMessage(string errorMessage)
        {
            ErrorMessage = errorMessage;
            return this;
        }

        public DialogValidationResultBuilder()
        {
            DialogPartResultIds = new System.Collections.Generic.List<string>();
            #pragma warning disable CS8603 // Possible null reference return.
            _errorMessageDelegate = new (() => string.Empty);
            #pragma warning restore CS8603 // Possible null reference return.
        }

        public DialogValidationResultBuilder(DialogFramework.Abstractions.DomainModel.IDialogValidationResult source)
        {
            if (source == null)
            {
                throw new System.ArgumentNullException("source");
            }
            DialogPartResultIds = new System.Collections.Generic.List<string>();
            _errorMessageDelegate = new (() => source.ErrorMessage);
            if (source.DialogPartResultIds != null) DialogPartResultIds.AddRange(source.DialogPartResultIds);
        }

        private System.Lazy<string> _errorMessageDelegate;
    }
#nullable restore
}

